packages:
  - 'storybook'
  - 'cloudflare-deploy-infra/builder'
  - 'cloudflare-deploy-infra/dispatcher'
  - 'cloudflare-code-review-infra'
  - 'cloudflare-auto-triage-infra'
  - 'cloudflare-auto-fix-infra'
  - 'cloud-agent'
  - 'cloud-agent/wrapper'
  - 'cloud-agent-next'
  - 'cloud-agent-next/wrapper'
  - 'cloudflare-app-builder'
  - 'cloudflare-ai-attribution'
  - 'cloudflare-db-proxy'
  - 'cloudflare-webhook-agent-ingest'
  - 'cloudflare-session-ingest'
  - 'cloudflare-o11y'
  - 'cloudflare-git-token-service'
  - 'kiloclaw'

ignoredBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - oxc-resolver
  - sharp
  - unrs-resolver

minimumReleaseAge: 5760

# Storybook 9.1.17 excluded for security update - https://storybook.js.org/blog/security-advisory/
minimumReleaseAgeExclude:
  - '@storybook/addon-docs@9.1.17'
  - '@storybook/addon-links@9.1.17'
  - '@storybook/addon-themes@9.1.17'
  - '@storybook/builder-webpack5@9.1.17'
  - '@storybook/core-webpack@9.1.17'
  - '@storybook/csf-plugin@9.1.17'
  - '@storybook/global@9.1.17'
  - '@storybook/icons@9.1.17'
  - '@storybook/nextjs@9.1.17'
  - '@storybook/preset-react-webpack@9.1.17'
  - '@storybook/react@9.1.17'
  - '@storybook/react-docgen-typescript-plugin@9.1.17'
  - '@storybook/react-dom-shim@9.1.17'
  - storybook@9.1.17

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - es5-ext
  - esbuild
  - libpq
  - workerd
